### ISSUE TITLE
Is this font readable?

### ISSUE THREAD

**Issue by jonfroehlich** [ASSETS-Conference/assets2022#11]
Hi team,

I wonder if this font is accessible (e.g., for people with low vision or dyslexia) given that it's a bit hard to read. I love the stylized look and how it fits into Athens, etc. and I think it's fine for the logo and landing page but not sure if it should be used for all other pages. Thoughts?

![image](https://user-images.githubusercontent.com/1621749/152162431-bf20af0b-c809-4997-a806-61be5469fa9e.png)

**Comment by judykong97** [comment]
<img width="1440" alt="Screen Shot 2022-02-03 at 6 08 45 PM" src="https://user-images.githubusercontent.com/15822762/152461197-48ac0c91-83c2-4e4a-82ef-f92df9d78d1d.png">
