### ISSUE TITLE
ASSETS'22 icon on subpages is pixelated

### ISSUE THREAD

**Issue by jonfroehlich** [ASSETS-Conference/assets2022#15]
Could probably be fixed by using a higher-resolution png?

![image](https://user-images.githubusercontent.com/1621749/152351588-6e683654-5e0e-4d7c-9c90-cff275cf2cd0.png)

**Comment by judykong97** [comment]
<img width="1440" alt="Screen Shot 2022-02-03 at 6 08 45 PM" src="https://user-images.githubusercontent.com/15822762/152460947-08d3adb6-9df9-45ee-a12f-c19f9cf3f5cf.png">
