### ISSUE TITLE
Mini-banner design updates

### ISSUE THREAD

**Issue by jonfroehlich** [ASSETS-Conference/assets2022#16]
![image](https://user-images.githubusercontent.com/1621749/152395769-c95d5b99-2725-4b4e-80da-8c0838097059.png)

I think the mini-banner on all pages except `index.html` needs to be updated:

- I'd like the dates of the conference to be in the banner (like the [ASSETS'21 webpage](https://assets21.sigaccess.org/sponsors_and_supporters.html)). There should be a nice clean way of doing this like we have on the landing page.
- The [icon is pixelated](https://github.com/EdigaHe/assets2022/issues/15) and needs to be updated
- The script font is hard to read. Either it should be bigger or we should change it to something more legible (https://github.com/EdigaHe/assets2022/issues/11)

**Comment by judykong97** [comment]
<img width="1440" alt="Screen Shot 2022-02-03 at 6 08 25 PM" src="https://user-images.githubusercontent.com/15822762/152460792-21937568-34bb-4b2e-bd9b-488e61b963c2.png">
<img width="1440" alt="Screen Shot 2022-02-03 at 6 08 45 PM" src="https://user-images.githubusercontent.com/15822762/152460802-139c321e-7b91-4196-b515-ba483105bef5.png">
