### ISSUE TITLE
Running the website locally and node.js requirement

### ISSUE THREAD

**Issue by jonfroehlich** [ASSETS-Conference/assets2022#19]
I typically dev with ["live server"](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) in VSCode so didn't notice this until @EdigaHe pointed it out.

## With Live Server
With "live server", the webpage doesn't load perfectly but it still loads (note the small issue with the navbar):
![image](https://user-images.githubusercontent.com/1621749/152899443-b4624759-4f87-459f-94f9-bb9edc36ff92.png)

## Simply double-clicking on index.html
Alternatively, when you simply open `index.html` locally in the browser, however, without live server things fail. I think because the website is built with `node.js`--and we use the latter to dynamically crossload pages like `navbar.html` and `footer.html`

![image](https://user-images.githubusercontent.com/1621749/152899972-b46c2064-15c6-4e0e-be44-63182477af7f.png)

## Questions
But perhaps someone can explain:
1. Why we are using node for such a simple website? I don't mean this critically--I genuinely want to know what's the design/implementation rationale here?
2. How to run the website locally so that it fully works

If we decide to continue to use `node.js` for the website, we should update the README.md with dev setup instructions.

I'm surprised that the ACM backend actually runs node... or did we have to do something special to get it to work (outside of FTPing our files over)

**Comment by jonfroehlich** [comment]
I see that there is the following in our README but it's again not clear why we need to run a local http server to run our website:

![image](https://user-images.githubusercontent.com/1621749/152994968-4adfb476-b1ff-4d37-a8ed-83e37dd3d816.png)

**Comment by judykong97** [comment]
We used node.js to separate the navbar / footer with the other content so we could develop separately without interfering with each other and without having to copy-and-paste the code a lot of times. 

We'll add a setup instruction about how to run it locally. Basically it's "install node.js on your computer, cd into the assets22-v1 folder, run `http-server -c-1`, and type http://localhost:8080 in browser". I think node.js requires a server to work properly (so we didn't need to set up anything additional for it to run outside of FTPing the files), and what we need to do is essentially setting up a local server, so I'm not sure why @jonfroehlich your live server didn't work, but we'll add instructions on how to run it.

**Comment by judykong97** [comment]
Updated README.md
