### ISSUE TITLE
Can we improve the information architecture of the menu headers?

### ISSUE THREAD

**Issue by jonfroehlich** [ASSETS-Conference/assets2022#2]
I've always found the information architecture of the ASSETS website a bit broken. It's hard to find things. I think the solution has been, generally, to throw everything into menu items on the menu header but then this becomes overwhelming.

For example, for the `Authors` menu header, I expect we could simplify this down to the most important links like the primary CFP + the individual tracks (e.g., Posters & Demos, Workshops). The other parts like Call for Mentoring, Submission Templates, Accessibility Mentorship, Creating Accessible PDFs, Making Accessible Presentations, Writing Guidelines, etc. don't seem to fit here. Could we either add new top-level menu headers or simply link to these within core pages themselves?

![image](https://user-images.githubusercontent.com/1621749/151214962-6875212f-ab8b-4021-9463-25a506134f34.png)

**Comment by EdigaHe** [comment]
@jonfroehlich We have re-structured those pages and make the top menu simpler and cleaner.
