### ISSUE TITLE
Making Accessible Presentations

### ISSUE THREAD

**Issue by jonfroehlich** [ASSETS-Conference/assets2022#22]
Should we put this sub-section on our [Guidelines and Policies page](https://assets22.sigaccess.org/guidelines-policies.html)?

It has it's own page on the [ASSETS2021 website](https://assets21.sigaccess.org/making_accessible_presentations.html)

![image](https://user-images.githubusercontent.com/1621749/153873169-6e73d819-9e6e-4183-8ca9-620f6e50e4e7.png)

**Comment by judykong97** [comment]
<img width="966" alt="Screen Shot 2022-03-07 at 3 06 10 AM" src="https://user-images.githubusercontent.com/15822762/157019718-c416ae52-d78c-4e37-9cd4-8e9ba3739a94.png">
