### ISSUE TITLE
Adding Code of Conduct page

### ISSUE THREAD

**Issue by jonfroehlich** [ASSETS-Conference/assets2022#23]
Can we copy over the ASSETS2021 [Code of Conduct webpage](https://assets21.sigaccess.org/code_of_conduct.html) and make appropriate changes for ASSETS2022.

This should be a top-level header in the menu bar.

**Comment by jayhersk** [comment]
Added, removed dates :)

**Comment by jonfroehlich** [comment]
Just putting in a screenshot. Deployed on test server: https://assets-conference.github.io/assets2022/assets22-v1/code-of-conduct.html

![image](https://user-images.githubusercontent.com/1621749/154275581-1111565d-0a6e-48d4-adaf-419b2a847ddf.png)
