### ISSUE TITLE
Rethink menu structure & organization

### ISSUE THREAD

**Issue by jayhersk** [ASSETS-Conference/assets2022#24]
Simplify, especially 'Authors' sub-menu

**Comment by jayhersk** [comment]
- Diversity & inclusion could go under code of conduct
- Authors could be split into two categories 
- Will make a mockup on the test server for feedback

**Comment by jonfroehlich** [comment]
With the new [TOC feature](https://github.com/ASSETS-Conference/assets2022/issues/27) and some other structural changes, I think we're pretty good here (still a bit overwhelming with the drop-down menus but it's too late to change now)

Closing...
