### ISSUE TITLE
Header images look blurry on iPhone only

### ISSUE THREAD

**Issue by jayhersk** [ASSETS-Conference/assets2022#26]

**Comment by jonfroehlich** [comment]
Adding examples.

Here's an example of the blurry background. 
![IMG_3546](https://user-images.githubusercontent.com/1621749/153969371-3eb8210a-a808-4186-84d3-6b618cf29064.PNG)

Instead, what we likely want is either a custom scaled image of the header for mobile (small-width screens) or a custom image that we use just for mobile. It should look more like this:
![IMG_3547](https://user-images.githubusercontent.com/1621749/153969348-9143ddc6-f0e8-43fa-8a6e-5a116fed6e80.PNG)

**Comment by jayhersk** [comment]
Jason suggestion: Look into special css properties for webkit

**Comment by jayhersk** [comment]
Fixed, see commit: 8716775de4b4bd00b762f7019d6cd7b0bf375f50

![IMG_8446](https://user-images.githubusercontent.com/15851295/186958861-2cf730ae-8621-48c0-872d-f7f5cf2a28b5.PNG)

![IMG_8447](https://user-images.githubusercontent.com/15851295/186958876-99205c6e-83bb-4014-9fe9-95b0c92cfef3.PNG)
