### ISSUE TITLE
Reorganize repo to remove 'assets22-v1'

### ISSUE THREAD

**Issue by jonfroehlich** [ASSETS-Conference/assets2022#28]
We should probably reorganize the repo to remove the `assets22-v1` folder and put all the contents in the main folder.

Thoughts?

**Comment by jonfroehlich** [comment]
So, my suggestion would be to refactor the folders so that everything is in the root folder:

https://assets-conference.github.io/assets2022/

Rather than

https://assets-conference.github.io/assets2022/assets22-v1/

**Comment by EdigaHe** [comment]
Fixed.
