### ISSUE TITLE
Consider moving inline styles into their own stylesheets

### ISSUE THREAD

**Issue by jonfroehlich** [ASSETS-Conference/assets2022#30]
I noticed we have lots of embedded `<style></style>` code in our html, which I think is generally [a web dev practice to avoid](https://www.thoughtco.com/avoid-inline-styles-for-css-3466846). I'm happy to defer to you all on this but I wonder why you decided to occasionally embed styles rather than consistently use `.css` sheets?

Here's an example from `index.html`:

![image](https://user-images.githubusercontent.com/1621749/154086388-ddd7e25a-90d3-4607-bc70-e7be3d7dcb82.png)

**Comment by jayhersk** [comment]
Fixed!
