### ISSUE TITLE
Possible to fix the auto-preview that gets generated for social media posts

### ISSUE THREAD

**Issue by jonfroehlich** [ASSETS-Conference/assets2022#31]
Hi team, I was posting about your awesome website this morning to LinkedIn and discovered that the auto-generated share snippet doesn't include our logo and the text preview talks about the pandemic rather than the conference.

![image](https://user-images.githubusercontent.com/1621749/154279157-67c2c569-f295-440a-8679-2d553fa83925.png)

Maybe this blog post would be useful:
https://marcgg.com/blog/2020/04/22/automatic-image-preview/

Feel free to close this issue if you don't think it's high enough priority to address. I know you have lots on your plate.

**Comment by ArkaneCow** [comment]
Addressed by #40 and awaiting for pull request to be reviewed. Basically, I just added the metadata tags required by both Facebook and LinkedIn (they are different) then tested a privately hosted version of the website with the link checker tools.

https://www.linkedin.com/post-inspector/inspect
https://developers.facebook.com/tools/debug/

![image](https://user-images.githubusercontent.com/1429346/159203224-49ed6e44-9103-4b54-a945-6017f90330dc.png)
![image](https://user-images.githubusercontent.com/1429346/159203256-ef29ebc4-a978-45fc-ac03-b5dc325591c9.png)

For now, I am using this image for the link preview: https://raw.githubusercontent.com/ASSETS-Conference/assets2022/main/design/logos/ASSETS2022_Logo.png

Do we want to keep using this image? If so, we should move it to the assets folder and compress it.

**Comment by EdigaHe** [comment]
I like it. What do you think @jonfroehlich ?

**Comment by ArkaneCow** [comment]
I’m noticing now that in addition to compressing, we should crop the preview image to have smaller height so that the words assets 2022 are visible.

**Comment by jonfroehlich** [comment]
Love it! Agree with you @ArkaneCow. You might need to tweak the preview image a bit to better show up in the share. We can also iterate once we start sharing on social media and seeing the results. Awesome job @ArkaneCow!

**Comment by EdigaHe** [comment]
I merged the PR and I think @ArkaneCow or anyone else can keep iterating on this directly in the main branch :)
