### ISSUE TITLE
TPC page

### ISSUE THREAD

**Issue by jonfroehlich** [ASSETS-Conference/assets2022#35]
We need to list the TPC on our webpage.

This is how [ASSETS'21](https://assets21.sigaccess.org/program_committee.html) did it.
![image](https://user-images.githubusercontent.com/1621749/156675464-a8603582-fa22-43d6-b5b3-a10ac897eb92.png)

I don't love the format, however, and would suggest instead something like this:

**Name in bold**, _institution_
**Name in bold**, _institution_
**Name in bold**, _institution_

Should be alphabetical.

**Comment by EdigaHe** [comment]
Added the page and formatted the list as suggested.

<img width="619" alt="Screen Shot 2022-03-06 at 7 25 31 PM" src="https://user-images.githubusercontent.com/3831526/156962669-eb5f6932-888b-4a30-b475-d2bcb98ed32e.png">

**Comment by jonfroehlich** [comment]
This is now deployed.

![image](https://user-images.githubusercontent.com/1621749/157543036-c3f56962-7e3d-46af-a2bc-ab9be700a41b.png)
