### ISSUE TITLE
Add Meta as a Gold sponsor

### ISSUE THREAD

**Issue by jonfroehlich** [ASSETS-Conference/assets2022#36]
Meta just came through as a Gold sponsor.

![image](https://user-images.githubusercontent.com/1621749/157716088-2c305f72-6370-4cf3-b270-4286aab15cc2.png)

Image from: https://commons.wikimedia.org/wiki/File:Meta_Platforms_Inc._logo.svg

Please add to https://assets22.sigaccess.org/sponsors.html page

**Comment by jonfroehlich** [comment]
Here's the logo that Meta just sent me that we can use:

![Meta_lockup_positive_primary_RGB](https://user-images.githubusercontent.com/1621749/158379145-e8902970-db05-4131-a56e-5c9eed148c1a.png)

**Comment by jonfroehlich** [comment]
Although given Apple's comments about their logo (https://github.com/ASSETS-Conference/assets2022/issues/37), probably best to use the Meta logo unmodified that they sent! :)

**Comment by judykong97** [comment]
<img width="531" alt="Screen Shot 2022-03-16 at 10 30 33 AM" src="https://user-images.githubusercontent.com/15822762/158651618-16bf620d-8609-4da0-ade5-f4053b13374f.png">

Updated the logo to be unmodified as they sent.
