### ISSUE TITLE
Update Apple logo

### ISSUE THREAD

**Issue by jonfroehlich** [ASSETS-Conference/assets2022#37]
Just received an email from Apple asking to update our logo on our webpage:

> Thank you so much for adding our logo to the ASSETS 2022 site. I shared it with our team that manages logo approvals, and they have asked for it to be updated to our latest version (black vs grey). I’ve added our logo sizing guidelines and the latest version of our logo below. Could you let me know once the logo has been updated?

![image](https://user-images.githubusercontent.com/1621749/158649377-aaa6191e-74a1-49d9-82e8-1831e8a4cb49.png)

Here's the logo to use:
![image](https://user-images.githubusercontent.com/1621749/158649409-88b1870a-3be6-411b-b0ae-3447f040d1cd.png)

**Comment by judykong97** [comment]
Done
