### ISSUE TITLE
Add Jason Wu to OC listing on webpage

### ISSUE THREAD

**Issue by jonfroehlich** [ASSETS-Conference/assets2022#38]
https://assets22.sigaccess.org/organizing-committee.html

![image](https://user-images.githubusercontent.com/1621749/159088334-e7273b3f-26f8-4dd5-9590-7d9b569d5f73.png)

**Comment by ArkaneCow** [comment]
sent out PR #39 to approvers

**Comment by EdigaHe** [comment]
Approved and merged into the main branch. Thanks!
