### ISSUE TITLE
Need to update important dates: the full paper deadline has passed and should have a strikethrough

### ISSUE THREAD

**Issue by jonfroehlich** [ASSETS-Conference/assets2022#44]
![image](https://user-images.githubusercontent.com/1621749/163994382-690ab3fb-10b2-4ac9-adad-299712f07cc6.png)

**Comment by judykong97** [comment]
<img width="824" alt="Screen Shot 2022-04-19 at 3 33 20 PM" src="https://user-images.githubusercontent.com/15822762/164112422-b5034cfa-603c-464e-a1c3-97cb41951d50.png">
<img width="886" alt="Screen Shot 2022-04-19 at 3 33 36 PM" src="https://user-images.githubusercontent.com/15822762/164112423-8dd235ac-5d36-4829-8d11-31159ff55af2.png">
