### ISSUE TITLE
Footer doesn't go to bottom of page

### ISSUE THREAD

**Issue by jonfroehlich** [ASSETS-Conference/assets2022#5]
The footer doesn't sit at the bottom of pages with no scroll:
![image](https://user-images.githubusercontent.com/1621749/151216051-8475b0df-3604-448f-96c4-6c690a9285b9.png)

I would either make:
(1) the footer larger vertically in these cases to take up more space (and extend down to the window automatically)
(2) or to clamp the footer at the bottom of the page, so there isn't strange whitespace after the footer

**Comment by EdigaHe** [comment]
We will not show coming soon pages. This issue only happens with coming soon pages.
