### ISSUE TITLE
Typo on ASSETS Poster/Demo CFP

### ISSUE THREAD

**Issue by jonfroehlich** [ASSETS-Conference/assets2022#50]
Huge just said this in Slack:

> we have a typo in the poster & demo CFP. For some reason, we are currently asking for a 4k-5k word paper, which corresponds to a 4-5 page double-column paper. On the Submission Guidelines section, it should read "Poster and demonstration 4-page submission should use a single-column template (around 1,300 words) found in ..."

We need to coordinate with them on exact language that they want.

**Comment by EdigaHe** [comment]
Fixed.
