### ISSUE TITLE
Need Program in menu bar

### ISSUE THREAD

**Issue by jonfroehlich** [ASSETS-Conference/assets2022#61]
Now that all papers and other content has been accepted into our conference, we should work ASAP on the program webpages, which include:

![image](https://user-images.githubusercontent.com/1621749/181386359-65f5d8b0-c022-438c-aece-1b9944c023f1.png)

In addition, we'll also want an "Accepted Workshops" menu item, we may also consider having a separate Workshops navbar item too.

**Comment by jayhersk** [comment]
Added to menu bar with one child item for now: 'Accepted Workshops'
Currently commented out. Will uncomment when we publish the Accepted Workshops page.

**Comment by jayhersk** [comment]
Pushed to live. Only has 'accepted workshops' so far, will update as we add pages.
