### ISSUE TITLE
Workshop page

### ISSUE THREAD

**Issue by jonfroehlich** [ASSETS-Conference/assets2022#62]
I think we need a workshop page that lists all of the accepted workshops and some info about them.

For each workshop, I think we include:

- Title of workshop
- Workshop url
- Abstract or CFP
- Lead organizers/contact info
- Possibly also key deadlines or, at least, how to participate

We have six accepted workshops at ASSETS'22:

![image](https://user-images.githubusercontent.com/1621749/181386634-44dcc60d-f624-4d81-8daf-6c5c599e8f6d.png)

For example, here's the info for our workshop: 

## The Future of Urban Accessibility for People with Disabilities: Data Collection, Analytics, Policy, and Tools

**Organizers:** Jon E. Froehlich, Yochai Eisenberg, Maryam Hosseini, Fabio Miranda
**Contact:** [urbanaccess2022@cs.uw.edu](mailto:urbanaccess2022@cs.uw.edu)
**Workshop website:** https://accessiblecities.github.io/UrbanAccess2022/
**Submission deadline:** Thurs, Sep 1 at 11:59PM AoE
**Virtual workshop date (tentative):** Monday, Oct 17th

There is widespread lack of accessibility in built environments, from roads and housing to public building and spaces. Such inaccessible urban infrastructure not only contributes to and further reinforces systemic exclusion of people with disabilities but also impacts public health, physical activity, and quality of life for all. To improve the design of our cities and to enable new accessibility-infused analytic tools and interactive maps, we need new data collection techniques, data standards, policies, and planning tools focused on the quality and accessibility of pathways, transit ecosystems, and buildings.

The goal of our “The Future of Urban Accessibility” workshop is to bring together a community of scholars and practitioners across disciplines, disability identities, cultures, and geographies to discuss the state of urban accessibility and the role of interactive technologies therein. We invite short papers, including experience reports, position papers, vision pieces, demonstrations, pictorials, or research summaries up to 2,000 words on this topic (references excluded). Papers should not be anonymized and, in addition to their primary content, should include a bio of each author and rationale for attending the workshop. Papers will be reviewed and selected by the co-organizers to balance topics, geographies, and communities of focus. Accepted authors will be required to register and virtually attend the workshop via Zoom on Mon, Oct 17th

Please submit your papers/artifacts [here](https://cmt3.research.microsoft.com/UrbanAccess2022/Submission/Index) by Thu, Sep 1 at 11:59PM AoE. We are using Microsoft's Conference Management Toolkit to handle submissions.

Our overarching goal is to identify open challenges, share current work across disciplines, and spur new collaborations. As a secondary goal, we aim to synthesize and publish our discussions together in a jointly authored report perhaps to the SIGACCESS Newsletter or beyond.

Please join us. We welcome your contributions! Email questions to: [urbanaccess2022@cs.uw.edu](mailto:urbanaccess2022@cs.uw.edu).

**Comment by jonfroehlich** [comment]
@jayhersk can you make a `workshops.html` or `accepted-workshops.html` skeleton for this and put "under construction" so we can link to it from our registration page (https://github.com/ASSETS-Conference/assets2022/issues/63)?

**Comment by jayhersk** [comment]
Added a page with placeholder data here: https://assets-conference.github.io/assets2022/accepted-workshops.html

![Screen Shot 2022-07-28 at 2 15 57 PM](https://user-images.githubusercontent.com/15851295/181608730-6b986870-df1f-49e3-a362-63287b2a93b6.png)

I will comment the placeholder info out for now and put 'Under construction', then I'll add it to the menu bar under 'Program' and link to it from the registration page :)

**Comment by jonfroehlich** [comment]
Love it. Thank you!

**Comment by jonfroehlich** [comment]
@jayhersk, I'd like you to deploy this page and just put TBD for things we don't yet know. We need/want to link this from our official registration page, so `accepted-workshops.html` needs to go live with all the info we do know.

We should also contact all the workshop organizers to have them fill out required data here: https://docs.google.com/document/d/1ApaXTrdKypVWDao6d7drj2XxlBHX8mBsXLY93l2Mowk/edit#heading=h.97sm8156o85s

**Comment by jayhersk** [comment]
Updated so far with two workshops that have posted their info! Also reached out to workshop co-chair to make sure that all authors have this document.

**Comment by jayhersk** [comment]
Still waiting on one website from workshop organizers I think? Will double check this.
