### ISSUE TITLE
Registration page

### ISSUE THREAD

**Issue by jonfroehlich** [ASSETS-Conference/assets2022#63]
This is a relatively urgent request. We need to put in a registration page linked in the menu bar `Attending -> Registration` like on the ASSETS'19 page:

![image](https://user-images.githubusercontent.com/1621749/181507827-159d36a6-05ac-48f9-b009-68e752b23701.png)

For the content, we've been using this [Google Doc](https://docs.google.com/document/d/1DeMRPst988zRxPV9hXo_1mDkdTwyJfVJ5COWIHhXCeI/edit#).

@jayhersk, for the registration tables, perhaps you can use that pretty format you came up with for the attending page?

Once this page is live, I also need to add links to it from our attending page.

**Comment by jayhersk** [comment]
Draft page on test server here: https://assets-conference.github.io/assets2022/registration.html

To do:
- Links (to Workshop and Attending Overview pages)
- Finalize text

**Comment by jonfroehlich** [comment]
This looks really great. Thank you!

Can we update the fee structure for the workshops to:

![image](https://user-images.githubusercontent.com/1621749/181607897-efab9051-1908-4ed6-b5e5-4737b29e784a.png)

**Comment by jayhersk** [comment]
Updated workshops cost table, also added links to attending-overview.html and accepted-workshops.html
(When pushing to live server, need to also push navbar and accepted-workshops as those changes are not yet live)

**Comment by jayhersk** [comment]
Done, pushed to live
