### ISSUE TITLE
Consider adding info on how to make .srt or .vtt files

### ISSUE THREAD

**Issue by jonfroehlich** [ASSETS-Conference/assets2022#67]
All of our pre-recorded content requires that the authors upload a supplementary .srt or .vtt file. Unsurprisingly, many in our community do not know how to do this. We just received the following email, which suggests that we should create a small lil "helper" page about how to do this:

> I was wondering if someone could help me with the requirements for the .srt file or point me in the right direction. These are the two approaches I found for creating the .srt file, is there one that is preferred for the video submission? 
> 
> 1. (This is what I tried to see if it worked) Download the transcript from Zoom recording (.vtt file) and convert it to .srt file. To view the structure I then converted that file to a .txt file. It has only the text that is transcribed. 
> 
> 2. (This method I found on YouTube) Create a .txt file that is formatted with sequence number, time code, and text for captioning (manual). Convert this file to .srt file.

I emailed back with:

> Yes, you can do this manually with a text editor but it's easier to use an online tool like [Flixier](https://flixier.com/tools/online-subtitle-editor) or [Rev](https://www.rev.com/blog/resources/what-is-an-srt-file-format-create-use-srt-files). If you have access to Adobe Premiere, it can auto-add captions based on speech-to-text, which you can then modify and export as .srt or .vtt: https://helpx.adobe.com/premiere-pro/using/working-with-captions.html

**Comment by judykong97** [comment]
<img width="898" alt="Screen Shot 2022-08-03 at 1 58 56 PM" src="https://user-images.githubusercontent.com/15822762/182710651-86f4801a-278c-44a2-968c-b7ddfa020ade.png">

Here's a draft - I added a paragraph to the policies-and-guidelines page into the existing "Creating Accessible Video Figures" section with the additional info. I also added Zoom and YouTube auto captioning - is it okay to include them?

**Comment by jonfroehlich** [comment]
The hybrid leadership team was meeting (coincidentally) just as you posted this and we reviewed it.

Overall, looks awesome!

A couple of things:
* Please add in that we do **not** want captions burned into videos (that is, do not integrate them into the video as pixels vs. having a separate file)
* Consider also adding in a reference to: https://dcmp.org/learn/captioningkey/600

**Comment by judykong97** [comment]
<img width="929" alt="Screen Shot 2022-08-03 at 2 27 00 PM" src="https://user-images.githubusercontent.com/15822762/182715227-4a15ba07-6669-4f4b-bfde-1eecd194e57d.png">

Updated with these changes

**Comment by judykong97** [comment]
<img width="942" alt="Screen Shot 2022-08-03 at 2 28 31 PM" src="https://user-images.githubusercontent.com/15822762/182715406-7d82cccd-e895-44ff-ad39-3de09bb74e27.png">

Updated with these changes

**Comment by jonfroehlich** [comment]
Oops, your text still says "text captions can be burned directly into the videos." This is **not** preferred. Instead, we want authors to create text files like .srt or .vtt

**Comment by judykong97** [comment]
Oh that paragraph was originally there for the video figures, maybe we'll just delete that sentence for the video figures (if there's no more to be submitted at this moment)? Right now the "do not" for video presentations are in the second paragraph

**Comment by judykong97** [comment]
<img width="933" alt="Screen Shot 2022-08-03 at 3 03 32 PM" src="https://user-images.githubusercontent.com/15822762/182720509-f684c3f8-24d9-4fec-a611-76b019901c26.png">

**Comment by jonfroehlich** [comment]
Looks good. Can we ship it?

(Note that I did not realize until just now that this was instructions both for video figures and video presentations but I agree that the instructions can be combined)

**Comment by judykong97** [comment]
Just shipped!

**Comment by jonfroehlich** [comment]
Thanks @judykong97!
