### ISSUE TITLE
Need to add 2G3R as bronze sponsor

### ISSUE THREAD

**Issue by jonfroehlich** [ASSETS-Conference/assets2022#70]
Here's their logo and [2G3R website](https://www.2g3r.com/)

![image](https://user-images.githubusercontent.com/1621749/183911950-e2ac6123-8dbc-4cac-8e13-a5d8619b79c8.png)

**Comment by judykong97** [comment]
<img width="509" alt="Screen Shot 2022-08-10 at 6 51 41 AM" src="https://user-images.githubusercontent.com/15822762/183918642-ce98f493-d909-48b5-92a7-2f782386a9e2.png">

Done

**Comment by jonfroehlich** [comment]
Thank you!
