### ISSUE TITLE
Add Miraikan as Bronze sponsor

### ISSUE THREAD

**Issue by jonfroehlich** [ASSETS-Conference/assets2022#72]
So excited to have Miraikan as a bronze sponsor. Please add them with this logo:

https://www.miraikan.jst.go.jp/_assets/img/global/header-logo-en-v.svg

(Don't forget to alt-text our logos too!)

**Comment by ArkaneCow** [comment]
done! live on main website here: https://assets22.sigaccess.org/sponsors.html

**Comment by jonfroehlich** [comment]
Looks great. Thanks Jason!
