### ISSUE TITLE
When you click on "Visa Support Letter" it takes you to wrong area of webpage

### ISSUE THREAD

**Issue by jonfroehlich** [ASSETS-Conference/assets2022#73]
https://assets22.sigaccess.org/attending-athens.html

![image](https://user-images.githubusercontent.com/1621749/184002076-c19086b1-08b9-439b-8450-6dfdf49993f1.png)

**Comment by judykong97** [comment]
Fixed. The page content overview was on a separate branch then and I wasn't aware of the additional id required for navigation.
