### ISSUE TITLE
Add accepted papers, demos/posters, DCs, and other artifacts to webpage

### ISSUE THREAD

**Issue by jonfroehlich** [ASSETS-Conference/assets2022#74]
See the email thread entitled "Should we make a webpage that lists all accepted content?"

> Some of you have suggested that with registration now open, that we should consider posting all accepted papers, demos, etc. to help inform people's decisions about whether to register.
> 
> So, I wanted to surface that idea here. If we think this is a reasonable idea, we would have to create a well-formatted website that shows all accepted content across the various tracks (say, an "Accepted Work" page at `accepted_work.html`).

We voted positively to do this. Hugo shared that actually it's been done before: https://assets21.sigaccess.org/accepted_papers.html

Someone in the TPC needs to share a spreadsheet of all accepted content and we need to come up with a clean HTML/CSS design to render it. I think it can go under the Program dropdown in navbar:

![image](https://user-images.githubusercontent.com/1621749/184145996-8125d43b-4021-4879-b297-8fdd3c3fcd61.png)

**Comment by jonfroehlich** [comment]
The TPC has delivered us a nice list of all accepted papers, authors, and affiliations (for primary paper track). 

It's in this [Google Doc](https://docs.google.com/document/d/1akKrxLi0xqp4VB9TIqWB5CEXwg60mqlLhZJQ6Ne9HS0/edit#)

**Comment by judykong97** [comment]
<img width="1033" alt="Screen Shot 2022-08-11 at 6 02 03 PM" src="https://user-images.githubusercontent.com/15822762/184266452-1d19ce61-b9a5-45ef-a941-814536fdb6b6.png">

Done. Should I publish?

**Comment by jonfroehlich** [comment]
Wow, that was incredibly fast. Let me send to TPC to see what they think. The paper title font is a bit large for my eyes (but maybe good for accessibility purposes!).

**Comment by jonfroehlich** [comment]
We now have accepted posters/demos listed here: https://docs.google.com/document/d/1hOFELf4Atiu9w_kStu8T7vVVZxz7QExRqhpG05OrIlo/edit#heading=h.kh7l1ap6prlw

(Can one of you give me access? I changed the GDoc to private so I could put it here and then lost access).

**Comment by judykong97** [comment]
It shows on my end that you have access to the doc (with your UW email) - can you access it now?

**Comment by judykong97** [comment]
Done with the draft
https://assets-conference.github.io/assets2022/accepted-posters-and-demos.html

I left a few comments in the google doc regarding things I noticed that might need double checking.

**Comment by jonfroehlich** [comment]
Wonderful. Just sent email to Hugo and Taslima to help respond to those comments/questions.

**Comment by jonfroehlich** [comment]
Here are the Experience Reports: https://docs.google.com/document/d/1-nvDRS9bi9wE4UBrPlZtnsnYICqfQxZ-NBxKuyzA3EM/edit?usp=sharing

**Comment by judykong97** [comment]
Thanks! I edited the posters and demos page according to the comments, and pushed to production. I should be able to work on the Experience Reports page in the next couple of days but needing a bit of time.

**Comment by jonfroehlich** [comment]
Thank you @judykong97. Totally get it.

**Comment by judykong97** [comment]
Sorry about the delay - Done. Here: https://assets-conference.github.io/assets2022/accepted-experience-reports.html 

c6272bcee6e53aa875f70ce9c3c05c80275a40ac 23593ba628413fb3abb50ae6a81bd6f54d1e6b05

**Comment by jonfroehlich** [comment]
Looks good!

(Note that if you reference this Issue in your commit comments (https://github.com/ASSETS-Conference/assets2022/issues/74), it will auto-show up here thereby creating a nice link between your code and the Issue).

**Comment by jonfroehlich** [comment]
I guess the last big one is accepted DCs? Can you work with the DC chairs on this? We're close!

**Comment by judykong97** [comment]
Done. The DC chairs got back with the content and I sent the draft page to the DC chairs. 
https://assets-conference.github.io/assets2022/accepted-doctoral-consortium.html

**Comment by judykong97** [comment]
The DC chairs thought the draft was good and I pushed the page to production. https://assets22.sigaccess.org/accepted-doctoral-consortium.html

All pages related to this issue should be done and in production right now.

**Comment by jonfroehlich** [comment]
Looks like a wonderful set of papers. Thanks @judykong97 for your great work here!
