### ISSUE TITLE
Add CREATE as a Gold Sponsor

### ISSUE THREAD

**Issue by jonfroehlich** [ASSETS-Conference/assets2022#78]
Please add CREATE as a Gold sponsor. Here's the logo.

![CREATE Logo](https://user-images.githubusercontent.com/1621749/184742098-ebb09d51-176a-41cb-a60a-039cfd72053d.png)

**Comment by judykong97** [comment]
<img width="1108" alt="Screen Shot 2022-08-16 at 3 55 00 AM" src="https://user-images.githubusercontent.com/15822762/184863057-06ff194e-f8a4-4db1-b12d-fc7261703205.png">

Done and in production.

**Comment by jonfroehlich** [comment]
Awesome work. Can we add a hyperlink to all of these logos so that they are clickable? (Now captured in this issue: https://github.com/ASSETS-Conference/assets2022/issues/79)

The CREATE logo should go to https://create.uw.edu/
