### ISSUE TITLE
Make sponsor logos clickable on landing page and sponsors page

### ISSUE THREAD

**Issue by jonfroehlich** [ASSETS-Conference/assets2022#79]
Logos should go to main webpage for the company.

**Comment by jonfroehlich** [comment]
@jayhersk I think this was your idea and I think it's a good one. Any possibility of getting this done quickly?

**Comment by ArkaneCow** [comment]
Hey i went ahead and implemented this!

**Comment by jonfroehlich** [comment]
Awesome. Just checked and everything looks correct except the Apple link, which goes to: https://assets22.sigaccess.org/apple.com/
