### ISSUE TITLE
Add Amazon as a gold sponsor

### ISSUE THREAD

**Issue by jonfroehlich** [ASSETS-Conference/assets2022#80]
Woohoo! Amazon has come in as a Gold sponsor.

Here's their official logo as an .SVG: https://commons.wikimedia.org/wiki/File:Amazon_logo.svg

And as a PNG:
![image](https://user-images.githubusercontent.com/1621749/185751217-b1c9e41d-7834-4474-8137-942dfd154511.png)

**Comment by ArkaneCow** [comment]
Implemented and pushed into production. For now, i did not make the logo size proportional to the sponsorship logo.
