### ISSUE TITLE
Add Microsoft as a gold sponsor

### ISSUE THREAD

**Issue by jonfroehlich** [ASSETS-Conference/assets2022#81]
I'm excited to announce that Microsoft has agreed to Gold sponsorship

SVG logo: https://commons.wikimedia.org/wiki/File:Microsoft_logo_%282012%29.svg

PNG: https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Microsoft_logo_%282012%29.svg/1280px-Microsoft_logo_%282012%29.svg.png

![image](https://user-images.githubusercontent.com/1621749/186226006-a9a5db10-82e3-4024-b2f7-05346d0415bd.png)

**Comment by jayhersk** [comment]
Done: c063de743b01a91babf07e01903989f75971ffe1

![Screen Shot 2022-08-26 at 1 28 41 PM](https://user-images.githubusercontent.com/15851295/186959825-22e48140-ed62-4e0d-97bb-ba743d81e0dc.png)
