### ISSUE TITLE
Add keynote speaker page

### ISSUE THREAD

**Issue by jonfroehlich** [ASSETS-Conference/assets2022#83]
Excitedly, we now have our two keynote speakers lined up (Haben Girma and Clayton Lewis). So, we have to make the page. :)

I started with the skeleton here: https://assets-conference.github.io/assets2022/keynote.html

For both keynotes, we need to add:
* Headshots with alt text (can we have the image float left within the container and the bio float right around that image, see https://habengirma.com/)
* Bio of keynote
* Keynote title
* Keynote abstract

I'd also like to have the left sidebar TOC on this page.

**Comment by jonfroehlich** [comment]
Clayton sent us his details.

alt text: head shot of Clayton Lewis

**Keynote Title:** Challenges and opportunities in technology for inclusion

**Abstract:** What will we be working on in the coming decade? This talk will consider a wide range of possibilities, ranging from predictable impacts of new technologies, to difficult matters of perspective and policy that influence the development and deployment of technology, to quixotic ambitions. The opinions will be those of the presenter, if even he endorses them.

Bio:
> Clayton Lewis is Emeritus Professor of Computer Science at the University of Colorado
Boulder. Lewis served previously as Co-Director for Technology for the Coleman
Institute for Cognitive Disabilities, and Fellow of the Institute of Cognitive Science, at
CU, and as technology advisor to the director of the National Institute for Disability and
Rehabilitation Research, US Department of Education. He is well known for his research
on evaluation methods in user interface design. Two methods to which he and his
colleagues have contributed, the thinking aloud method and the cognitive walkthrough,
are in regular use in software development organizations around the world. He has also
contributed to cognitive assistive technology, to programming language design, to
educational technology, and to cognitive theory in causal attribution and learning.
>
> Before joining the University of Colorado, Lewis was Manager of Human Factors at
IBM’s Watson Research Center, where he was a member of the research staff from 1970
to 1973 and 1979 to 1984. He holds degrees from Princeton, MIT, and the University of
Michigan. He has been honored by appointment to the ACM SIGCHI Academy, by the
SIGCHI Social Impact Award, and by the Strache Leadership Award (CSUN Assistive
Technology Conference).

![ClaytonLewis](https://user-images.githubusercontent.com/1621749/186438038-ef962ae7-e479-4f57-95e8-fb0171c56451.jpg)

**Comment by jonfroehlich** [comment]
Here's Haben's info

Bio
The first Deafblind person to graduate from Harvard Law School, Haben Girma is a human rights lawyer advancing disability justice. President Obama named her a White House Champion of Change. She received the Helen Keller Achievement Award, a spot on the Forbes 30 Under 30 list, and TIME100 Talks. President Bill Clinton, Prime Minister Justin Trudeau, and Chancellor Angela Merkel have all honored Haben. Haben believes disability is an opportunity for innovation, and she teaches organizations the importance of choosing inclusion. The New York Times, Oprah Magazine, and TODAY Show featured her memoir, Haben: The Deafblind Woman Who Conquered Harvard Law.

Photo alt text:
A 30-ish, Black woman with long dark hair and hazel eyes, wearing a textured red top and a thoughtful expression. The background has shades of blue. 

![HabenGirma](https://user-images.githubusercontent.com/1621749/186663928-a297abb4-a0c5-4039-a0f1-6a0ffe64189b.jpg)

**Comment by jayhersk** [comment]
Live on test server: https://assets-conference.github.io/assets2022/keynote.html

Still need to add link to navbar

**Comment by jonfroehlich** [comment]
Wonderful. Thanks @jayhersk. I just made some slight aesthetic changes. Can you crop Clayton's picture so it is the same aspect ratio as Haben's (so longer on the vertical than the horizontal; this will help with symmetry on the page and also make Clayton's longer bio look shorter).

![image](https://user-images.githubusercontent.com/1621749/186776238-623de273-0dc1-4593-8f31-c4d7186589be.png)

**Comment by jayhersk** [comment]
Live here: https://assets22.sigaccess.org/keynote.html

Will update with more info as we have it :)
