### ISSUE TITLE
Add NIDILRR as silver sponsor

### ISSUE THREAD

**Issue by jonfroehlich** [ASSETS-Conference/assets2022#85]
The National Institute on Disability, Independent Living and Rehabilitation Research (NIDILRR) has come in as a Silver sponsor ($3k)—woohoo! 🎉

Here's is their logo: https://acl.gov/sites/default/files/graphics/NIDILRRColorRGB.jpg. Can we add them to our webpage? Remember to hyperlink the logo back to: https://acl.gov/about-acl/about-national-institute-disability-independent-living-and-rehabilitation-research

![image](https://user-images.githubusercontent.com/1621749/187512934-5138263e-382d-4eb1-b494-b13adf87a483.png)

**Comment by jonfroehlich** [comment]
@jayhersk, @judykong97, @ArkaneCow can one of you please add this to the webpage?

**Comment by judykong97** [comment]
Done
<img width="333" alt="Screen Shot 2022-09-28 at 5 28 35 AM" src="https://user-images.githubusercontent.com/15822762/192779344-3d6e7880-e7c0-4cd3-ab9b-143545677740.png">
