### ISSUE TITLE
Add Twitter as a silver sponsor ($3k)

### ISSUE THREAD

**Issue by jonfroehlich** [ASSETS-Conference/assets2022#87]
Please add Twitter as a silver sponsor ($3k). Remember to link to twitter.com. Logo below from: https://about.twitter.com/en/who-we-are/brand-toolkit

![2021 Twitter logo - blue](https://user-images.githubusercontent.com/1621749/192655676-d9e7bc05-a0af-40f6-b3bb-d0824a470eeb.png)

**Comment by judykong97** [comment]
Done
<img width="333" alt="Screen Shot 2022-09-28 at 5 28 35 AM" src="https://user-images.githubusercontent.com/15822762/192779258-3c15b08e-8008-4bae-8b79-db84b06d1cd2.png">
