### ISSUE TITLE
Add Studio Pacifica as a Bronze sponsor

### ISSUE THREAD

**Issue by jonfroehlich** [ASSETS-Conference/assets2022#88]
![image](https://user-images.githubusercontent.com/1621749/192822436-bbc9e123-17ca-47b5-9b90-1483187ea9e4.png)

Link: https://studiopacificaseattle.com/

**Comment by judykong97** [comment]
Done
<img width="464" alt="Screen Shot 2022-09-28 at 10 20 41 AM" src="https://user-images.githubusercontent.com/15822762/192847973-bac90b42-f8cf-468f-afdc-467181a42116.png">

**Comment by jonfroehlich** [comment]
Amazing. Thank you @judykong97!
