### ISSUE TITLE
Online program updates for v1.1

### ISSUE THREAD

**Issue by jonfroehlich** [ASSETS-Conference/assets2022#90]
- [x] Improve color contrast. From Christian: "I just ran the website through WAVE, and it seems that the headings for the program are pretty low contrast (white on purple in small font). Can this get fixed?" - Christian
- [x] Add in left sidebar TOC so that at least the days show up on the floating sidebar TOC menu
- [x] Add "at-a-glance" overview for all three days
- [x] Add in virtual/hybrid events
- [x] "can someone please update that program on the website? at 7:30 on the second day, the word "roundtable" needs to be removed from that event title, please" - Kelly Mack
- [x] Firefox compatibility. "Thank you so much for all your hard work putting up the program and dealing with the updates and changes. I have one request to check, I use Firefox, and this is the view I have (not sure if it's something funky with my own browser settings). Also when I click the button, I have to click twice to get it to collapse - it defaults to expanded."

![image](https://user-images.githubusercontent.com/1621749/194313521-efb6fd97-dcda-43c6-b640-b861fa0042cb.png)

- [x] "We've added the Session Chairs (just beneath each session name) and Best Paper Nominees. Could you please update the program to show this information? You might have ideas for what works best for indicating best paper noms (last year they had little ribbons). You can search by "[Best Paper Nominee] in the doc (I also highlighted it in pale yellow): https://docs.google.com/document/d/1uXl27qvpsqEp2dURbfxn4Haz9DJYmbPFQ0LcHlq71V4/edit?usp=sharing Thank you for bearing with us "

**Comment by jonfroehlich** [comment]
We still need an "at-a-glance" overview for all three days. Here's an example from UIST:

![image](https://user-images.githubusercontent.com/1621749/195848706-048ad911-6d9c-4fa9-90cf-ec97275ef3cc.png)

Actually, I think it would be important to have **four** days in there, starting with Sun, Oct 23 that would capture the DC and when the registration desk is open.

**Comment by jonfroehlich** [comment]
I think all of these things have been addressed. Just needs to be pushed to production.

**Comment by jayhersk** [comment]
Program at a glance updated:
<img width="1260" alt="Screen Shot 2022-10-15 at 6 09 29 PM" src="https://user-images.githubusercontent.com/15851295/196009442-f242ce88-89cb-4e14-a68e-b36840e93e76.png">

Potential future task?
- [ ] Add links to all items in program at a glance to jump to detailed schedule, or event details on another page

**Comment by jayhersk** [comment]
Updated with links and times:

![Screen Shot 2022-10-19 at 8 08 45 PM](https://user-images.githubusercontent.com/15851295/196827183-a6672f9c-3a3f-45fd-8e7f-f9fcfd2c2d73.png)

**Comment by jonfroehlich** [comment]
This is done and amazing! Thank you @jayhersk!
