### ISSUE TITLE
Images broken on landing page and attending-athens.html

### ISSUE THREAD

**Issue by jonfroehlich** [ASSETS-Conference/assets2022#92]
I refactored the location of images yesterday and I suspect this folder never got pushed to production: `\assets\img\attending`

Broken images on `index.html`
![image](https://user-images.githubusercontent.com/1621749/196035626-25725e77-1f76-48a6-b6a1-db34e01f0cd4.png)

Broken images on `attending-athens.html`
![image](https://user-images.githubusercontent.com/1621749/196035651-65cb6ff0-21f4-4210-b5f2-5f11da4b6f24.png)

![image](https://user-images.githubusercontent.com/1621749/196035656-43af19f4-06b4-4645-b28d-409b3356ebdd.png)

![image](https://user-images.githubusercontent.com/1621749/196035668-adf754a2-a97f-4c71-9b08-22fd2fac2991.png)

**Comment by EdigaHe** [comment]
Images uploaded to FTP server.
